baseurl = "https://wearexavir.netlify.app/"
title = "Vir & Xavi"
theme = "theme_wearexavir"
languageCode = "en-us"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  TwitterID = "weareXaVir"
  SpotifyID = "your_spotify"
  YoutubeID = "weareXaVir"
  InstagramID = "weareXaVir"
  TwitchID = "weareXaVir"
  Name = "weareXaVir"
  HeaderUsername = "weareXaVir"
  HeaderHostname = "gohugo.io"
  Email = "we.are.xavir@gmail.com"
  About = "Hi!"
  ProfilePicture = "/logo_wy.png"
  Favicon = "/favicon.ico"

